## AMBIENTE 

In [103]:
import numpy as np
import random

In [316]:
"""
Exemplo de Q( ESTADO , AÇÕES )

Q = np.zeros( (3,3,4) )
Significa que você tem uma Matriz 3 x 3 com 9 possibilidade de ESTADOS
( neste caso, jogo da velha, são posições espaciais)
e em casa posição você tem 4 posibilidades AÇÔES (imagine um jogo com cima, baixo, esquerda, direita)
"""

"""
Veja que não iremos colocar ações aqui, pois só existe uma por player... 1 para p1 e -1 para p2...
ou seja, o player 1 só pode jogar X... ele não pode jogar W, K, B etc...  fixando o exemplo do personagem,
imagine que você pode ir para cima, baixo, esquerda e direita... temos aqui 4 estados possíveis
"""
Q = np.zeros( (3,3) )
Q

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [458]:
class Game(qLearning):
    
    def __init__(self):
        
        """
        As perspectivas de vitórias e derrota são sempre
        relacionadas com o player 1 (p1), ele é o nosso
        jogador principal (máquina que será treinada)
        """
        super().__init__()
        self.board = np.zeros((3,3))
        self.p1 = 1 
        self.p2 = -1
    
    # reset game
    def reset (self):
        self.board = np.zeros((3,3))
    
    # draw board
    def draw_board(self):
        
        draw = ''

        for i in range(3):
            for j in range(3):
                simbolo = ''
                # simbolo X (p1 = 1) ou O (p2 = -1)
                if game.board[i][j] == 1:
                    symbol = 'X'
                elif game.board[i][j] == -1:
                    symbol = 'O'
                else:
                    symbol = ' '


                draw += '|'+symbol+''



                if j == 2:

                    draw +='|\n-------\n'
        
        print(draw)
    
    # jogada - Human
    def select_pos_by_human(self, player, name):
        
        while True:
            row = int( input(name+' row :') )
            col = int( input(name+' col :') )

            # Tem que checar se a posição está ocupada
            if self.board[row,col] == 0:
                self.board[row,col] = player
                break
            else:
                print('p1 escolha outra posição...')
        return row,col
    
    # jogada - Random 
    def select_pos_by_random(self, player, name):
        
        # get INDEX row and col equals zero (posição livre pra jogar)
        available_pos = np.where( game.board == 0 )

        row = available_pos[0]
        col = available_pos[1]

        # list_index_available
        list_index_available = [[r,c] for r,c in zip(row,col)]

        # sort one randomly
        row_col = random.sample(list_index_available, k = 1)[0]

        row = row_col[0] # Linha
        col = row_col[1] # Coluna

        self.board[row][col] = player
        
        print(name + f' jogou na posição { str(row_col) }')
    
        return row,col
    
    # jogada - QLearning
    def select_pos_by_q(self, player, name):
        
    
        if np.random.uniform(0, 1) <= self.epsilon:
            self.select_pos_by_random(player =  player, name =  name)
            
        else:
            
            # pegue o ÍNDICE com o  ESTADO na tabela Q com maior valores
            q_max_pos = np.where( self.Q == np.max(self.Q) )

            row = q_max_pos[0][0]
            col = q_max_pos[1][0]
            
            print(q_max_pos, row, col)

            # Jogar no Tabuleiro
            self.board[row][col] = player
            
            return row,col
    
    # chegar vencedor
    def check_win(self):
        
        # Row
        if sum(self.board[0]) == 3 or sum(self.board[1]) == 3 or sum(self.board[2]) == 3:
            #print('venceu')
            return 1
        if sum(self.board[0]) == -3 or sum(self.board[1]) == -3 or sum(self.board[2]) == -3:
            #print('perdeu')
            return -1
        # Col
        if sum(self.board[:,0]) == 3 or sum(self.board[:,1]) == 3 or sum(self.board[:,2]) == 3:
            #print('venceu')
            return 1
        if sum(self.board[:,0]) == - 3 or sum(self.board[:,1]) == - 3 or sum(self.board[:,2]) == - 3:
            #print('perdeu')
            return -1
        # Diagonal
        if sum(game.board.diagonal()) == 3 or sum(np.fliplr(game.board).diagonal()) == 3:
            #print('venceu')
            return 1
        if sum(game.board.diagonal()) == -3 or sum(np.fliplr(game.board).diagonal()) == -3:
            #print('perdeu')
            return -1
        # Empate
        if not 0 in self.board:
            #print('empate')
            return 0
        
        # continua = 2, empate = 0, vitoria = 1, derrota = -1
        return 2
        
    # iniciar o Jogo
    def start(self):
        
        print ( 'player 1 = X\nplayer 2 = O\n')
        while True:
            
            # player 1 joga
            #pos = self.select_pos_by_q(self.p1, name = 'player 1')
            pos = self.select_pos_by_random(self.p1, name = 'player 1')
            # desenhar jogada do player 1
            self.draw_board()
            # checa resultado
            if self.check_win() != 2: # continua = 2, empate = 0, vitoria = 1, derrota = -1
                
                self.update_q(
                    row    = pos[0],
                    col    = pos[1],
                    reward = self.reward(result = self.check_win() )
                )
                break
            
            
            # player 2 joga
            pos = self.select_pos_by_random(self.p2, name = 'player 2')
            # desenhar jogada player 2
            self.draw_board()
            # checar resultado
            if self.check_win() != 2: # continua = 2, empate = 0, vitoria = 1, derrota = -1
                
                self.update_q(
                    row    = pos[0],
                    col    = pos[1],
                    reward = self.reward(result = self.check_win() )
                )
                break
        
        
        estado = self.check_win() # ESTADO
    
        if estado == 1:
            print('venceu')
        if estado == -1:
            print('perdeu')
        if estado == 0:
            print('empate')
        
        #return estado # ESTADO
        
        


game = Game()
game.board

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [464]:
game.reset()
game.start()

player 1 = X
player 2 = O

player 1 jogou na posição [0, 0]
|X| | |
-------
| | | |
-------
| | | |
-------

player 2 jogou na posição [1, 0]
|X| | |
-------
|O| | |
-------
| | | |
-------

player 1 jogou na posição [2, 1]
|X| | |
-------
|O| | |
-------
| |X| |
-------

player 2 jogou na posição [2, 2]
|X| | |
-------
|O| | |
-------
| |X|O|
-------

player 1 jogou na posição [1, 1]
|X| | |
-------
|O|X| |
-------
| |X|O|
-------

player 2 jogou na posição [2, 0]
|X| | |
-------
|O|X| |
-------
|O|X|O|
-------

player 1 jogou na posição [1, 2]
|X| | |
-------
|O|X|X|
-------
|O|X|O|
-------

player 2 jogou na posição [0, 2]
|X| |O|
-------
|O|X|X|
-------
|O|X|O|
-------

player 1 jogou na posição [0, 1]
|X|X|O|
-------
|O|X|X|
-------
|O|X|O|
-------

venceu


In [465]:
game.Q

[[0, 2.21949, 0], [0, 0, 0], [1.629, 0.9, 0]]

### Testes para criar o Ambiente

In [248]:
game.board

array([[ 1., -1., -1.],
       [ 1.,  1.,  1.],
       [-1.,  1., -1.]])

In [392]:
game.Q

[[0, 0, 0], [0, 0.1, 0], [0.08100000000000002, 0, 0]]

In [222]:
printar = ''

for i in range(3):

    for j in range(3):
        simbolo = ''
        # simbolo X (p1 = 1) ou O (p2 = -1)
        if game.board[i][j] == 1:
            symbol = 'X'
        elif game.board[i][j] == -1:
            symbol = 'O'
        else:
            symbol = ' '
            
        
        printar += '|'+symbol+''
        
        
        
        if j == 2:
            
            printar +='|\n-------\n'
    

print(printar)

| | |X|
-------
| |O|X|
-------
|O| |X|
-------



In [123]:
# np.where ( LISTA == VALOR ) - pega os índices de acordo com os valores
# random.sample(list_index_available, k = 1)[0] - pega uma amostra aleatoriamente

# get INDEX row and col equals zero (posição livre pra jogar)
available_pos = np.where(game.board == 0)


row = available_pos[0]
col = available_pos[1]

# list_index_available
list_index_available = [[r,c] for r,c in zip(row,col)]

# sort one
row_col = random.sample(list_index_available, k = 1)[0]

row = row_col[0]
col = row_col[1]

game.board[row][col] , row_col

In [88]:
list_index_available

[(1, 2), (2, 0), (2, 1), (2, 2)]

In [27]:
game.select_pos(0,2,-1)

In [38]:
game.board[0,1]

0.0

In [247]:
# np.diagonal() - Pega a DIAGONAL deu uma matriz 2x2

game.board.diagonal() # Diagonal 1

array([ 1.,  1., -1.])

In [246]:
#np.fliplr( MATRIZ ) + diagonal() - Pega a diagonal contrária

np.fliplr(game.board).diagonal() # Diagonal 2

array([-1.,  1., -1.])

In [252]:
# testando se consigo comparar condição com matriz 2x2

if 1 in game.board:
    print('printou')

printou


## Q Learning

In [401]:
class qLearning(object):

    
    def __init__(self):
        # Tabela Q (Estados , Ações ) Ações são 1 apenas (X)
        #self.Q = np.zeros( (3,3) )
        self.Q_value = [
            [0,0,0],
            [0,0,0],
            [0,0,0]
        ]
        self.Q_status = {} # Cada ação 
        # the percentage of tiem when we should take the best action
        self.epsilon = 0.2
        # Discount for future rewards
        self.gamma   = 0.9
        # learning rate - the rate at which the AI agent should learn
        self.lr      = 0.9

    
    def reward(self, result):
        if result == 1:  # Vitória
            return 1
        if result == -1: # Derrota
            return 0
        if result == 0:  # Empate
            return 0.5
    
    def update_q(self, row, col, reward):
        
        self.Q[row][col] = self.Q[row][col] + self.lr*( reward + self.gamma* np.max(self.Q) - self.Q[row][col] )
        
    

In [319]:
Q[2][1] = 1

In [324]:
np.max(Q)

1.0

In [396]:
# Exemplo de herança de classe

class Personagem(object):
    k = 10
    def __init__(self, nome):
        self.nome = nome
        
    def ataque(self, alvo):
        alvo.hp -= self.mp

# Raças 
class Dracula(Personagem):
    def __init__(self,nome):
        super().__init__(nome)
        self.hp = 100
        self.mp = 10            
class Ghoust(Personagem):
    def __init__(self,nome):
        super().__init__(nome)
        self.hp = 50
        self.mp = 30

p1 = Dracula('player 1')
p2 = Ghoust('player 2')

p1.ataque(p2)
p2.hp

40