In [1]:
import numpy as np
import random
import pandas as pd

In [2]:
x = [1,2,3,4,5,6,7,8,9]
# Transforma 1D em 2D
np.reshape(x, (-1, 3)) 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
# Transforma 2D em 1D
#game.board.flatten()

In [4]:
class Game():
    
    def __init__(self):

        
        # tipo de jogada
        #self.style = style
        
        
        # Player
        self.player = 1 # player1 = 1      player2 = -1
        
        # Board (é nosso ESTADO ATUAL)
        self.board = np.zeros((3,3))
        
        
        # Set of States
        self.states = []
        
        # Posição Atual
        self.pos = 0 # ex: '(1, 1)'
        
        # Q_table -> (states, actions, Q_value )
        self.Q_table = {
            'states' : [],
            'actions': ['(0, 0)','(0, 1)','(0, 2)','(1, 0)','(1, 1)','(1, 2)','(2, 0)','(2, 1)','(2, 2)'],
            'Q': []
        }
        
        
        # Caminho
        self.path = {
            'states':  [], # boards
            'actions': [], # posição no tabuleiro
        } # Appends como string... (COPY os objetos... se não eles se alteram)
        
        self.resultados ={
            'win':0,
            'draw':0,
            'lost':0
            }
        
    
    # Caso queira visualizar melhor a Tabela
    def Q_table_df(sef):
        
        df = pd.DataFrame(
            index=game.Q_table['states'],
            columns=game.Q_table['actions'],
            data = game.Q_table['Q']
            )
            #data = 0 )
        return df
        
        
            
    def reset_game(self):
        self.board = np.zeros((3,3))
        self.player = 1
        self.path = {
            'states': [],
            'actions':[],
        }
    
    def draw_board(self):
        
        draw = ''

        for i in range(3):
            for j in range(3):
                simbolo = ''
                # simbolo X (p1 = 1) ou O (p2 = -1)
                if game.board[i][j] == 1:
                    symbol = 'X'
                elif game.board[i][j] == -1:
                    symbol = 'O'
                else:
                    symbol = ' '


                draw += '|'+symbol+''



                if j == 2:

                    draw +='|\n-------\n'
        
        print(draw)
        
    def available_moves(self):
        return np.argwhere(self.board == 0)
    
    def available_move_choice(self):
        return random.choice(self.available_moves())
    
        
    def check_win(self):
        
        # Row
        if sum(self.board[0]) == 3 or sum(self.board[1]) == 3 or sum(self.board[2]) == 3:
            #print('venceu')
            return 1
        if sum(self.board[0]) == -3 or sum(self.board[1]) == -3 or sum(self.board[2]) == -3:
            #print('perdeu')
            return -1
        # Col
        if sum(self.board[:,0]) == 3 or sum(self.board[:,1]) == 3 or sum(self.board[:,2]) == 3:
            #print('venceu')
            return 1
        if sum(self.board[:,0]) == - 3 or sum(self.board[:,1]) == - 3 or sum(self.board[:,2]) == - 3:
            #print('perdeu')
            return -1
        # Diagonal
        if sum(game.board.diagonal()) == 3 or sum(np.fliplr(game.board).diagonal()) == 3:
            #print('venceu')
            return 1
        if sum(game.board.diagonal()) == -3 or sum(np.fliplr(game.board).diagonal()) == -3:
            #print('perdeu')
            return -1
        # Empate
        if not 0 in self.board:
            #print('empate')
            return 0
        
        # continua = 2, empate = 0, vitoria = 1, derrota = -1
        return 2
     
    def resultado(self, resultado):
        if resultado == 1:
            #print('venceu')
            self.resultados['win'] += 1
            
        elif resultado == -1:
            #print('perdeu')
            self.resultados['lost'] += 1

        else:
            #print('empate')
            self.resultados['draw'] += 1

        
            
    def reward(self, result):
        if result == 1:  # Vitória
            return 1
        if result == -1: # Derrota
            return -5
        if result == 0:  # Empate
            return 0.1
    
    def update_Q(self, reward):
        
        lr = 0.9 # Alpha
        gamma = 0.9
        
        states_actions = list( self.path.values() )
        
        states =  list( reversed( states_actions[0] ) )
        actions = list( reversed( states_actions[1] ) )

        index = 0
        for s2, a2 in zip(states,actions):
            
            try:
                
                
                
                if index == 0:
                    ##### pegar o index numérico dos States e Actions
                    s2 = self.Q_table['states'].index(str(s2))
                    a2 = self.Q_table['actions'].index(str(a2))
                    self.Q_table['Q'][s2][a2] += lr*( reward ) #+ gamma*np.max( self.Q_table['Q'][s2] ) - self.Q_table['Q'][s2][a2] )
                    
                    
                    # Fazer o mesmo, mas agora para o States adiantado
                    # Next Value

                    # ESTADO avançado
                    index += 1

                    s1 = states[index]
                    s1 = self.Q_table['states'].index(str(s1))

                    a1 = actions[index]
                    a1 = self.Q_table['actions'].index(str(a1))
                    # a2 -> deixa em aberto, por que estamos interessado na ação com valor máximo do respectivo ESTADO avançado


                    self.Q_table['Q'][s1][a1] += lr*( 0 + gamma*np.max( self.Q_table['Q'][s2] ) - self.Q_table['Q'][s1][a1] )

                
                else:
                    
                    reward = 0

                    
                    #print(s1,a1)
                    #input()
                    ##### pegar o index numérico dos States e Actions
                    s2 = self.Q_table['states'].index(str(s2))
                    a2 = self.Q_table['actions'].index(str(a2))


                    # Fazer o mesmo, mas agora para o States adiantado
                    # Next Value

                    # ESTADO avançado
                    index += 1

                    s1 = states[index]
                    s1 = self.Q_table['states'].index(str(s1))

                    a1 = actions[index]
                    a1 = self.Q_table['actions'].index(str(a1))
                    # a2 -> deixa em aberto, por que estamos interessado na ação com valor máximo do respectivo ESTADO avançado


                    self.Q_table['Q'][s1][a1] += lr*( reward + gamma*np.max( self.Q_table['Q'][s2] ) - self.Q_table['Q'][s1][a1] )

                
                
                
            except IndexError:
                continue
                #game.Q_table['Q'][s2][a2] += lr*( reward + gamma*np.max( game.Q_table['Q'][s2] ) - game.Q_table['Q'][s2][a2] )

    
    
        # jogada - Random 
    def select_pos_by_random(self, player, name):
        
        row_col = self.available_move_choice()
        
        row = row_col[0] # Linha
        col = row_col[1] # Coluna

        self.board[row][col] = player
        
        self.pos = row,col
        
        #print(name + f' jogou na posição { str(self.pos) }')
    
        # jogada - Human
    def select_pos_by_input(self, player, name):
        
        # desenhar jogada do player 
        self.draw_board()
        while True:
            row = int( input('Row: ') )
            col = int( input('Col: ') )
            
            if [row,col] in self.available_moves().tolist(): # Refransforme Em lista... Array ele aceita 
                
                self.board[row][col] = player
                self.pos = row,col
                break
            else:
                input('try other position...')
            
        
        #print(name + f' jogou na posição { str(self.pos) }')
    
    def select_pos_by_Q(self,player, name):
        
        # Veja o estado atual seu (Seu board)... pegue a ação com maior Q
        
        
        epsilon = 0.0
        # jogada Aleatória
        if np.random.uniform(0, 1) <= epsilon:
            self.select_pos_by_random( self.player, name = 'player '+str(self.player) )
            
            
            #print('usando aleatório')
        
        # Vai na tabela e joga
        else:
            
            # Se existir esse estado gravado...
            
            if str(self.board) in self.Q_table['states']:
                
                
                #print('usando o Q')
                
                
                index_state = self.Q_table['states'].index( str(self.board) )
                #index_action= self.Q_table['Q'][index_state].index( str(np.max(self.Q_table['Q'][index_state])) )
                #index_qmax = np.argmax(self.Q_table['Q'][index_state])
                
                
                # pega todos valores de Q com respectivo index state na ordem DESCRESCENTE
                # assim, se a posição máx já estiver ocupada, ele vai pro segundo maior e assim por diante.
                
                #print(sorted( self.Q_table['Q'][index_state], reverse = True ) )
                #input()
                
                
                
                # pega o maior decrescente... logo se for Zero não temos estado treinado
                for qmax in sorted( self.Q_table['Q'][index_state], reverse = True ):
                    
                    if qmax == 0:
                        self.select_pos_by_random( self.player, name = 'player '+str(self.player) )
                        break
                    
                    
                    index_qmax = self.Q_table['Q'][index_state].index( qmax )
                    
                    action = self.Q_table['actions'][index_qmax]
                    
                    row = int(action[1:2])
                    col = int(action[4:5])
                    
                    if [row,col] in self.available_moves().tolist(): # Refransforme Em lista... Array ele aceita  
                    
                        self.board[row][col] = player

                        self.pos = row,col
                        
                        break
                        
            
            
            # se não existir, joga aleatório mesmo
            else:
                self.select_pos_by_random( self.player, name = 'player '+str(self.player) )

            
              
                
    # iniciar o Jogo
    def start(self):
        #print ( 'player 1 = X\nplayer 2 = O\n')
        
        while True:
            
            ##################### Criação da Tabela Q (antes) ###################
            # Se não existe este Estado
            if str(self.board) not in self.Q_table['states']: 
                # 1-) Adicionar Estado Atual
                self.Q_table['states'].append( str(self.board ) )
                # 2-) registrar movimento - NÃO PRECISA, POIS ELES NÃO SÃO VARIADOS... SÃO SEMPRE 9 POSSÍVEIS
                #self.Q_table['actions'].append( str(self.pos ) )
                # 3-) Add valor de Q
                self.Q_table['Q'].append( [0,0,0,0,0,0,0,0,0] )
            ###############################################################
            
            
            
            # Registrar o State Inicial
            self.path['states'].append( str(self.board) )
    
            
            # player (movimento) -> Ação
            if self.player == 1: # PLAYER 1
                self.select_pos_by_Q( self.player, name = 'player '+str(self.player) )
                
            else:               # PLAYER 2 
                self.select_pos_by_random( self.player, name = 'player '+str(self.player) )
                
            
            
            # Registrar o action
            self.path['actions'].append( str(self.pos) )
            
            """##################### Criação da Tabela Q (após a jogada) ###################
            # Se não existe este Estado
            if str(self.board) not in self.Q_table['states']: 
                # 1-) Adicionar Estado Atual
                self.Q_table['states'].append( str(self.board ) )
                # 2-) registrar movimento - NÃO PRECISA, POIS ELES NÃO SÃO VARIADOS... SÃO SEMPRE 9 POSSÍVEIS
                #self.Q_table['actions'].append( str(self.pos ) )
                # 3-) Add valor de Q
                self.Q_table['Q'].append( [0,0,0,0,0,0,0,0,0] )
            ###############################################################"""
            
            # desenhar jogada do player 
            #self.draw_board()
            
            
            # checa resultado
            if self.check_win() != 2: # continua = 2, empate = 0, vitoria = 1, derrota = -1
                
                reward = self.reward( self.check_win() )
                
                self.resultado(self.check_win())
                
                self.update_Q( self.check_win() )
                
                self.reset_game()
                
                break
            
            
            # Mudar jogador    
            self.player *= -1 # switch players  
        

In [50]:
game = Game()

In [51]:
for i in range(100):
    game.start()

In [28]:
game.Q_table_df()

(0, 0)      (0, 1)  \
[[0. 0. 0.]\n [0. 0. 0.]\n [0. 0. 0.]]             0.000000    0.000000   
[[0. 0. 0.]\n [0. 0. 0.]\n [0. 0. 1.]]           312.228221  154.766700   
[[ 0.  0.  0.]\n [-1.  0.  0.]\n [ 0.  0.  1.]]    0.000000    0.000000   
[[ 0.  0.  0.]\n [-1.  0.  1.]\n [ 0.  0.  1.]]  381.420000  201.600000   
[[ 0.  0.  0.]\n [-1.  0.  1.]\n [ 0. -1.  1.]]    0.000000    0.000000   
[[ 0.  0.  0.]\n [ 0.  0. -1.]\n [ 0.  0.  1.]]    0.000000    0.000000   
[[ 0.  0.  0.]\n [ 0.  0. -1.]\n [ 1.  0.  1.]]   72.084669  182.970000   
[[ 0.  0.  0.]\n [-1.  0. -1.]\n [ 1.  0.  1.]]    0.000000    0.000000   
[[ 0.  0.  0.]\n [-1.  1. -1.]\n [ 1.  0.  1.]]   90.613638   50.130000   
[[-1.  0.  0.]\n [-1.  1. -1.]\n [ 1.  0.  1.]]    0.000000    0.000000   
[[ 0.  0.  0.]\n [ 0. -1.  0.]\n [ 0.  0.  1.]]    0.000000    0.000000   
[[ 0.  0.  0.]\n [ 0. -1.  1.]\n [ 0.  0.  1.]]    0.000000    0.000000   
[[ 0.  0. -1.]\n [ 0. -1.  1.]\n [ 0.  0.  1.]]    0.000000    0.000000   
[[ 0.  0. -1.]\n [ 0. -1.  1.]\n [ 0.  1.  1.]]    0.000000    0.000000   
[[ 0. -1.  0.]\n [ 0.  0.  0.]\n [ 0.  0.  1.]]    0.000000    0.000000   
[[ 0. -1.  0.]\n [ 0.  0.  0.]\n [ 0.  1.  1.]]   77.493682    0.000000   
[[ 0. -1.  0.]\n [ 0.  0.  0.]\n [-1.  1.  1.]]    0.000000    0.000000   
[[ 0. -1.  1.]\n [ 0.  0.  0.]\n [-1.  1.  1.]]   15.546111    0.000000   
[[ 0. -1.  1.]\n [ 0.  0. -1.]\n [-1.  1.  1.]]    0.000000    0.000000   
[[ 0. -1.  1.]\n [ 0.  1. -1.]\n [-1.  1.  1.]]    0.000000    0.000000   
[[ 0. -1.  1.]\n [-1.  1. -1.]\n [-1.  1.  1.]]   45.000000    0.000000   
[[-1.  0.  0.]\n [ 0.  0.  0.]\n [ 0.  0.  1.]]    0.000000    0.000000   
[[-1.  0.  1.]\n [ 0.  0.  0.]\n [ 0.  0.  1.]]    0.000000    0.000000   
[[-1.  0.  1.]\n [ 0.  0. -1.]\n [ 0.  0.  1.]]    0.000000    0.000000   
[[-1.  0.  1.]\n [ 0.  0. -1.]\n [ 1.  0.  1.]]    0.000000    0.000000   
[[-1.  0.  1.]\n [-1.  0. -1.]\n [ 1.  0.  1.]]    0.000000    0.000000   
[[-1.  1.  1.]\n [-1.  0. -1.]\n [ 1.  0.  1.]]    0.000000    0.000000   
[[ 0. -1.  0.]\n [ 0. -1.  0.]\n [ 0.  1.  1.]]    0.000000    0.000000   
[[ 0.  0.  0.]\n [ 0.  0.  0.]\n [-1.  0.  1.]]    0.000000    0.000000   
[[ 0.  1.  0.]\n [ 0.  0.  0.]\n [-1.  0.  1.]]    0.000000    0.000000   
...                                                     ...         ...   
[[-1.  1.  0.]\n [ 1. -1.  1.]\n [-1. -1.  1.]]    0.000000    0.000000   
[[-1.  0.  0.]\n [ 1.  0.  1.]\n [-1. -1.  1.]]    0.000000   51.595754   
[[-1.  1.  0.]\n [ 1.  0.  1.]\n [-1. -1.  1.]]    0.000000    0.000000   
[[ 1. -1.  1.]\n [-1. -1.  0.]\n [-1.  1.  1.]]    0.000000    0.000000   
[[-1. -1.  1.]\n [ 1.  0. -1.]\n [-1.  1.  1.]]    0.000000    0.000000   
[[ 0.  0. -1.]\n [-1.  1.  0.]\n [ 1. -1.  1.]]   52.200000    0.000000   
[[ 0. -1. -1.]\n [ 1. -1.  0.]\n [ 0.  1.  1.]]    0.000000    0.000000   
[[ 1.  0.  0.]\n [-1. -1.  1.]\n [ 1. -1.  1.]]    0.000000  -11.700000   
[[ 1.  1. -1.]\n [ 0. -1.  1.]\n [ 0. -1.  1.]]    0.000000    0.000000   
[[-1.  0. -1.]\n [ 1. -1.  1.]\n [ 0.  1.  1.]]    0.000000  -11.700000   
[[ 0.  1.  0.]\n [ 0. -1. -1.]\n [ 1. -1.  1.]]   23.166001    0.000000   
[[ 1.  1.  0.]\n [ 0. -1. -1.]\n [ 1. -1.  1.]]    0.000000    0.000000   
[[ 1.  1. -1.]\n [ 0. -1. -1.]\n [ 1. -1.  1.]]    0.000000    0.000000   
[[-1.  1. -1.]\n [ 1.  0.  1.]\n [-1. -1.  1.]]    0.000000    0.000000   
[[ 1.  0.  1.]\n [-1. -1.  0.]\n [ 1. -1.  1.]]    0.000000  -11.700000   
[[ 0. -1.  0.]\n [-1. -1.  1.]\n [ 0.  1.  1.]]    0.000000    0.000000   
[[-1.  0. -1.]\n [ 0.  1.  1.]\n [-1.  0.  1.]]    0.000000    0.000000   
[[ 0.  1.  0.]\n [ 1. -1. -1.]\n [-1.  1.  1.]]    0.000000    0.000000   
[[-1. -1.  1.]\n [ 0.  1. -1.]\n [-1.  1.  1.]]    0.000000    0.000000   
[[-1.  0.  1.]\n [ 1. -1.  0.]\n [-1.  1.  1.]]    0.000000    0.000000   
[[-1.  0.  1.]\n [ 1. -1. -1.]\n [-1.  1.  1.]]    0.000000    0.000000   
[[ 1. -1.  0.]\n [ 1. -1. -1.]\n [-1.  1.  1.]]    0.000000    0.000000   
[[ 

In [52]:
game.resultados

{'win': 55, 'draw': 9, 'lost': 36}

In [21]:
#save = game.Q_table.copy()

In [47]:
game.Q_table = save